// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Task struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Title       string         `json:"title"`
	Status      string         `json:"status"`
	Priority    int64          `json:"priority"`
	DueAt       sql.NullString `json:"due_at"`
	CompletedAt sql.NullString `json:"completed_at"`
	CreatedAt   string         `json:"created_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	FullName  string         `json:"full_name"`
	Bio       sql.NullString `json:"bio"`
	CreatedAt string         `json:"created_at"`
}
