// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const completeTask = `-- name: CompleteTask :execrows

UPDATE tasks
SET status = 'done', completed_at = datetime('now')
WHERE id = ? AND status <> 'done'
`

// The `(sqlc.narg(x) IS NULL OR col = sqlc.narg(x))` trick is how you do an
// OPTIONAL filter without building SQL strings at runtime. One prepared
// statement, two behaviours. Note the query planner may not use the index
// for this shape -- at high scale, write two explicit queries instead.
// :execrows returns the affected-row count, which is how you distinguish
// "updated" from "id did not exist" without a prior SELECT.
func (q *Queries) CompleteTask(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeTask, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countTasksByStatus = `-- name: CountTasksByStatus :many
SELECT status, COUNT(*) AS total
FROM tasks
WHERE user_id = ?
GROUP BY status
ORDER BY status
`

type CountTasksByStatusRow struct {
	Status string `json:"status"`
	Total  int64  `json:"total"`
}

// Aggregates: sqlc infers the result type of COUNT(*) as int64.
func (q *Queries) CountTasksByStatus(ctx context.Context, userID int64) ([]CountTasksByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countTasksByStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTasksByStatusRow
	for rows.Next() {
		var i CountTasksByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, priority, due_at)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, user_id, title, status, priority, due_at, completed_at, created_at
`

type CreateTaskParams struct {
	UserID   int64          `json:"user_id"`
	Title    string         `json:"title"`
	Priority int64          `json:"priority"`
	DueAt    sql.NullString `json:"due_at"`
}

// sqlc.arg(name) gives the generated Go param a readable name instead of
// Column1/Column2. Worth doing on every query with more than two params.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.Priority,
		arg.DueAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, full_name, bio)
VALUES (?, ?, ?)
RETURNING id, email, full_name, bio, created_at
`

type CreateUserParams struct {
	Email    string         `json:"email"`
	FullName string         `json:"full_name"`
	Bio      sql.NullString `json:"bio"`
}

// ===========================================================================
// query.sql -- you write SQL. sqlc writes the Go.
//
// Every query carries a magic comment:
//
//	-- name: <GoFuncName> :<kind>
//
// kinds:
//
//	:one       -> returns exactly one row  (Go: (Row, error), sql.ErrNoRows if none)
//	:many      -> returns a slice          (Go: ([]Row, error))
//	:exec      -> returns nothing but err  (Go: error)
//	:execrows  -> returns rows affected    (Go: (int64, error))
//	:execlastid-> returns last insert id   (Go: (int64, error)) -- sqlite/mysql
//	:copyfrom  -> bulk load                (postgres only, COPY protocol)
//	:batchexec -> pipelined batch          (postgres + pgx only)
//
// This file is the ONLY place SQL lives. No ORM query builder, no string
// concatenation in Go, no runtime surprises.
// ===========================================================================
// RETURNING lets us get the full row back in ONE round trip instead of
// insert-then-select. Supported by sqlite 3.35+, postgres, and mariadb.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.FullName, arg.Bio)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTasksByStatus = `-- name: DeleteTasksByStatus :execrows
DELETE FROM tasks WHERE user_id = ? AND status = ?
`

type DeleteTasksByStatusParams struct {
	UserID int64  `json:"user_id"`
	Status string `json:"status"`
}

func (q *Queries) DeleteTasksByStatus(ctx context.Context, arg DeleteTasksByStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTasksByStatus, arg.UserID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTask = `-- name: GetTask :one

SELECT id, user_id, title, status, priority, due_at, completed_at, created_at FROM tasks WHERE id = ? LIMIT 1
`

// sqlc.narg() = "nullable arg": the Go param becomes sql.NullString rather
// than string, so you can genuinely pass NULL. sqlc.arg() on a nullable
// column would force you to always send a value.
func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTasksByIDs = `-- name: GetTasksByIDs :many
SELECT id, user_id, title, status, priority, due_at, completed_at, created_at FROM tasks WHERE id IN (/*SLICE:ids*/?)
`

// sqlc.slice() expands to the right number of placeholders at call time --
// the single hardest thing to do safely by hand with database/sql.
func (q *Queries) GetTasksByIDs(ctx context.Context, ids []int64) ([]Task, error) {
	query := getTasksByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.DueAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, email, full_name, bio, created_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, bio, created_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT
    t.id,
    t.title,
    t.status,
    t.priority,
    t.due_at,
    u.email      AS user_email,
    u.full_name  AS user_name
FROM tasks t
JOIN users u ON u.id = t.user_id
WHERE t.user_id = ?1
  AND (?2 IS NULL OR t.status = ?2)
ORDER BY t.priority DESC, t.id ASC
`

type ListTasksByUserParams struct {
	UserID int64       `json:"user_id"`
	Status interface{} `json:"status"`
}

type ListTasksByUserRow struct {
	ID        int64          `json:"id"`
	Title     string         `json:"title"`
	Status    string         `json:"status"`
	Priority  int64          `json:"priority"`
	DueAt     sql.NullString `json:"due_at"`
	UserEmail string         `json:"user_email"`
	UserName  string         `json:"user_name"`
}

// A JOIN produces a NEW anonymous row type. sqlc generates a dedicated
// struct (ListTasksByUserRow) with exactly these columns -- not a Task.
func (q *Queries) ListTasksByUser(ctx context.Context, arg ListTasksByUserParams) ([]ListTasksByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByUser, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByUserRow
	for rows.Next() {
		var i ListTasksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.DueAt,
			&i.UserEmail,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, full_name, bio, created_at FROM users ORDER BY created_at DESC, id DESC LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Bio,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overdueTasks = `-- name: OverdueTasks :many
SELECT t.id, t.title, t.due_at, u.email
FROM tasks t
JOIN users u ON u.id = t.user_id
WHERE t.due_at IS NOT NULL
  AND t.due_at < ?1
  AND t.status <> 'done'
ORDER BY t.due_at ASC
`

type OverdueTasksRow struct {
	ID    int64          `json:"id"`
	Title string         `json:"title"`
	DueAt sql.NullString `json:"due_at"`
	Email string         `json:"email"`
}

func (q *Queries) OverdueTasks(ctx context.Context, now sql.NullString) ([]OverdueTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, overdueTasks, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OverdueTasksRow
	for rows.Next() {
		var i OverdueTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DueAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
