// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// The `(sqlc.narg(x) IS NULL OR col = sqlc.narg(x))` trick is how you do an
	// OPTIONAL filter without building SQL strings at runtime. One prepared
	// statement, two behaviours. Note the query planner may not use the index
	// for this shape -- at high scale, write two explicit queries instead.
	// :execrows returns the affected-row count, which is how you distinguish
	// "updated" from "id did not exist" without a prior SELECT.
	CompleteTask(ctx context.Context, id int64) (int64, error)
	// Aggregates: sqlc infers the result type of COUNT(*) as int64.
	CountTasksByStatus(ctx context.Context, userID int64) ([]CountTasksByStatusRow, error)
	// sqlc.arg(name) gives the generated Go param a readable name instead of
	// Column1/Column2. Worth doing on every query with more than two params.
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// ===========================================================================
	// query.sql -- you write SQL. sqlc writes the Go.
	//
	// Every query carries a magic comment:
	//
	//   -- name: <GoFuncName> :<kind>
	//
	// kinds:
	//   :one       -> returns exactly one row  (Go: (Row, error), sql.ErrNoRows if none)
	//   :many      -> returns a slice          (Go: ([]Row, error))
	//   :exec      -> returns nothing but err  (Go: error)
	//   :execrows  -> returns rows affected    (Go: (int64, error))
	//   :execlastid-> returns last insert id   (Go: (int64, error)) -- sqlite/mysql
	//   :copyfrom  -> bulk load                (postgres only, COPY protocol)
	//   :batchexec -> pipelined batch          (postgres + pgx only)
	//
	// This file is the ONLY place SQL lives. No ORM query builder, no string
	// concatenation in Go, no runtime surprises.
	// ===========================================================================
	// RETURNING lets us get the full row back in ONE round trip instead of
	// insert-then-select. Supported by sqlite 3.35+, postgres, and mariadb.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTasksByStatus(ctx context.Context, arg DeleteTasksByStatusParams) (int64, error)
	// sqlc.narg() = "nullable arg": the Go param becomes sql.NullString rather
	// than string, so you can genuinely pass NULL. sqlc.arg() on a nullable
	// column would force you to always send a value.
	GetTask(ctx context.Context, id int64) (Task, error)
	// sqlc.slice() expands to the right number of placeholders at call time --
	// the single hardest thing to do safely by hand with database/sql.
	GetTasksByIDs(ctx context.Context, ids []int64) ([]Task, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// A JOIN produces a NEW anonymous row type. sqlc generates a dedicated
	// struct (ListTasksByUserRow) with exactly these columns -- not a Task.
	ListTasksByUser(ctx context.Context, arg ListTasksByUserParams) ([]ListTasksByUserRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	OverdueTasks(ctx context.Context, now sql.NullString) ([]OverdueTasksRow, error)
}

var _ Querier = (*Queries)(nil)
